TEST_NAMES= test1 test2  # Replace these with your .cpp files!
TESTING_DIR = ..         # This should provide location of Makefile-testing.mk

include $(TESTING_DIR)/Makefile-testing.mk  # Leave as-is.
