TEST_NAMES= ActionMap Collection data_collect EmptyOrganism Genome MABEBase MABE MABEScript ManagerModule ModuleBase Module Organism OrganismManager OrgIterator OrgType Population SigListener TraitSet ErrorManager ErrorManager_debug TraitInfo TraitManager 
TESTING_DIR = ..

include $(TESTING_DIR)/Makefile-testing.mk
