TEST_NAMES= VirtualCPU_Inst_Flow VirtualCPU_Inst_IO VirtualCPU_Inst_Label VirtualCPU_Inst_Manipulation VirtualCPU_Inst_Math VirtualCPU_Inst_Nop VirtualCPU_Inst_Replication
TESTING_DIR = ../..

include $(TESTING_DIR)/Makefile-testing.mk
